# Components package initialization
from .navbar import create_navbar
from .upload_component import create_upload_component
from .privacy_assessment import create_privacy_assessment_tab
from .data_quality import create_data_quality_tab
from .chatbot_component import create_chatbot_component, process_chat_message, create_bot_message
from .knowledge_manager import create_knowledge_manager_component
